package-lock.json
This  change generated by "npm install" command, updates URL for webpack to use `https:` rather than `http:`
=> Update to package-lock.json

src/eterna/constraints/constraints/ConsecutiveBaseConstraint.ts
This change clearly restores the expected highlighting for consecutive base count constraints.   
However the member name `maxConsecutive`  is a bit misleading, since it is the maximum + 1.   This change corrects the code calling `EPars.getRestrictedConsecutive` to use `maxConsecutive - 1`.   I've avoided a more satisfying change such as renaming it or changing the semantic of the stored value since it is `public` and may stored (serialized) as part of puzzles.  
Fixes: #192
=> Fix consecutive base constraint highlights

src/eterna/resources/BitmapManager.ts
Caching Textures in BitmapManager did not account for attributes like font, size, color or bold, resulting in sometimes inconsistent text color.  E.g. under some circumstances base numbers might show up in red, rather than white.
Fixes: #69 
Fixes: #185
Minor note: branch name I used was fix_29 rather than the more logical fix_69.
=> Fix BitmapManager caching to account for color

multiplatform/mkdirp.js
mkDirSync() fails on ubuntu, when the target directory already exists.
=> fix build on ubuntu

src/eterna/EternaApp.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/puzzle/PuzzleManager.ts, src/eterna/rscript/RNAScript.ts, src/eterna/rscript/ROPPopPuzzle.ts, src/eterna/rscript/ROPPre.ts, src/eterna/rscript/ROPShowMissionScreen.ts, src/eterna/rscript/RSignals.ts
Can be done using the following tools:
`PRE-PushPuzzle` directive
`PopPuzzle` command (to call from the second puzzle, to go back to the main puzzle)
`ShowMissionScreen` command
**Testable with Puzzle `9386663` on Eterna-dev**
resolves #253
=> Support Puzzle Switching

src/eterna/rscript/RScriptUIElement.ts
Nucleotide palette highlight was misplaced because it used the local position instead of the world position of the target.
Needed by [Nova Tutorial 1.1](https://www.pbs.org/wgbh/nova/labs//lab/rna/research#/nceg/1/1) / Eterna-dev puzzle `9386588`
=> Fix positioning of highlight on certain UI elements

src/eterna/pose2D/Pose2D.ts, src/eterna/rscript/RNAScript.ts, src/eterna/rscript/ROPHighlight.ts, src/eterna/rscript/ROPTextbox.ts
`ShowArrowEnergy` command for making arrows point to an energy score.
Support highlighting of energy scores.
Needed by [Nova Tutorial 4.1](https://www.pbs.org/wgbh/nova/labs//lab/rna/research#/nceg/4/1) / Eterna-dev puzzle `9386710`
=> Energy Scores Fixes & Improvements

src/eterna/pose2D/RNALayout.ts
If 4 or less nucleotides, display a straight RNA instead of a circle.
Needed by [Nova Tutorial 1.1](https://www.pbs.org/wgbh/nova/labs//lab/rna/research#/nceg/1/1) / Eterna-dev `9386588`
=> Make RNA of 4 or less nucleotides straight instead of circular

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/pose2D/Pose2D.ts, src/eterna/ui/NucleotideRangeSelector.ts, src/eterna/ui/TextInputPanel.ts, src/eterna/ui/Toolbar.ts
resolves #299 
Puzzle IDs for testing:
* No pip mode: 9386699
* With pip mode: 9386716
* Accessible through the hamburger menu or 'V' hotkey.
* Takes the sequence length into account to initialize the dialog. 
* In PiP mode, it takes the minimum of the length across the sequences.
* It remembers the last entered range
* A 'Clear range' button is shown if a range was set, that clears and displays all nucleotides.
=> Nucleotide range selector

src/eterna/net/EternaURL.ts, src/eterna/util/Utility.ts, src/eterna/util/__tests__/Utility.test.ts
- Replaces `generateParameterString` with `URLSearchParams` across the application
[#Issue https://github.com/eternagame/EternaJS/issues/211]
=> fix/Remove-Duplicate function (functionality)

src/eterna/UndoBlock.ts
TESTS CURRENTLY FAIL - I had to run to sleep, and I couldn't figure out why the test failed. IDK If it fails on dev or not, I will check tomorrow if no one merges by then.
In case it's just on my machine due to a global library, here are the errors:
```(node:27024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added. Use emitter.setMaxListeners() to increase limit
(node:27024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added. Use emitter.setMaxListeners() to increase limit
FAIL src/eterna/folding/__tests__/Folder.test.ts (11.013s)
× linearfoldC:MFETests (114ms)````
```● linearfoldC:MFETests
expect(received).resolves.toBeUndefined()
Received promise rejected instead of …
```
=> Implemented ANY_PAIR in the undo block

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/rscript/RNAScript.ts, src/eterna/rscript/ROPUIArrow.ts, src/eterna/rscript/ROPUITooltip.ts, src/eterna/rscript/RScriptEnv.ts, src/eterna/ui/help/HelpToolTip.ts
2 new instructions `ShowUIArrow` and `ShowUITooltip`
Their corresponding elements stick to their target even if the screen is resized. 
To replace  `ShowArrowLocation`:
* (Show|Hide)UIArrow elementId [top|bottom]
* Example: `ShowUIArrow G;`
To replace combinations of `ShowArrowLocation` and `ShowTextboxLocation`:
* (Show|Hide)UITooltip elementId, text, [top|bottom], [tailLength]
* Example: `ShowUITooltip toggletarget, "Target mode shows the desired shape", top, 45;`
=> Dynamic arrows

src/eterna/pose2D/Pose2D.ts
Make sure bases are marked in all poses when using the base marking button in PiP - (same behavior as ctrl+click).
=> Fix base marking in PiP mode

src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
Resolves #127 
This checks that all constraints are satisfied prior to submission; there is an existing check for just the sequence. Presumably, this would cover player-made constraints, since the only other constraints (available in the puzzlemaker), pair count constraints, are also checked.
=> All constraints must be satisfied for submission

src/eterna/constraints/ConstraintBar.ts, src/eterna/constraints/ConstraintBox.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
Resolves #240 
This prevents constraints from displaying a state number if the puzzle is single-state
=> Single-state constraints don't show a state number

src/eterna/constraints/ConstraintBox.ts, src/eterna/constraints/constraints/MaximumMutationConstraint.ts
Resolves #408 
When the numbers are too large, a newline is inserted. The text is moved up and the text underneath it is moved down.
=> Fix overflow for max mutation/consecutive bases constraints

src/eterna/constraints/ConstraintBar.ts, src/eterna/mode/DesignBrowser/ViewSolutionOverlay.ts, src/eterna/ui/EternaMenu.ts, src/eterna/ui/Toolbar.ts, src/eterna/ui/TrueWidthDisplay.ts, src/eterna/vfx/LightRay.ts, src/flashbang/input/DisplayObjectPointerTarget.ts, src/flashbang/input/PointerCapture.ts, src/flashbang/input/PointerTarget.ts, src/flashbang/layout/HLayoutContainer.ts, src/flashbang/objects/Button.ts, src/flashbang/objects/GraphicsObject.ts, src/flashbang/objects/SceneObject.ts
Resolves #384 
This hides the zoom buttons (as is done on the app) on small screens and moves the palette up a row. If the screen is small enough, it also moves the mark bases and swap pairs buttons to the same row as the palette.
=> Toolbar is handled correctly on small screens

src/eterna/Feedback.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/puzzle/SolutionManager.ts
I'm sure it could be more beautiful, and I'm currently ignoring the (not relevant for coloring) signal to noise data. I am sure we could just put them in a text box somewhere.
One pain of course is that the schema doesn't quite match between degradation data and other shape data. Confronted with the choice of either splitting all the behavior of all our functions (s.t. `getShapeMins` could do one of two things) and splitting the data itself into two buckets, I did the latter.
=> degradation data in FeedbackViewMode

src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/pose2D/Pose2D.ts
It's a bit of a hack -- still relies on the various puzzle editing operations (in particular, mutations) to trigger a check for `changed` that targetConditions can trigger -- but it's a lot better than rejiggering a lot more logic.
=> Puzzlemaker now saves TargetConditions in undo stack

src/flashbang/util/StyledTextBuilder.ts
Eg, in constraint stat text where subsections were not getting properly recolored
=> Fix overriding PIXI.TextStyle-derived styles in StyledTextBuilder

src/eterna/mode/PoseEdit/PoseEditMode.ts
When loading an autosave, even though there are no annotations, the annotation manager is called to update the annotations. This caused a crash on progression puzzles, where we don't initialize the annotations panel.
=> Fix crash in progression when loading autosave

src/eterna/pose2D/Pose2D.ts, src/eterna/pose2D/RNALayout.ts, src/eterna/ui/PoseThumbnail.ts
These type of calls are expensive for long sequences and are no longer necessary:
```
const xmin: number = Math.min(...xarray);
const xmax: number = Math.max(...xarray);
const ymin: number = Math.min(...yarray);
const ymax: number = Math.max(...yarray);
```
=> Determine RNA sequence bounds in one traversal instead of four

src/eterna/mode/PoseEdit/PoseEditMode.ts
As a note: The issue here was that the target condition for the pose index was being used, rather than that for the state being evaluated
=> Fix molecule showing in non-pip mode and improve variable naming

src/eterna/EPars.ts, src/eterna/UndoBlock.ts, src/eterna/constraints/constraints/ShapeConstraint.ts, src/eterna/folding/Folder.ts, src/eterna/folding/NuPACK.ts, src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/pose2D/Pose2D.ts, src/eterna/puzzle/Puzzle.ts, src/eterna/rnatypes/Oligo.ts
* Fix comment on reorderedOligosIndexMap, which described the map as going in the wrong direction
* Fix shape constraint _targetAlignedConstraints and _targetAlignedNaturalPairs which used the backwards interpretation of reorderedOligosIndexMap
* Fix delta energy calculation in multistrand puzzles, where the oligo order of the pose was always used for the sequence rather than the desired target/native oligo order (which could also cause a crash)
* Change Oligo mode from static members to enum
* Create new rnatypes file for Oligo and OligoMode
* Fix sequence highlights not respecting target oligo order in target mode (namely for binding and shape constraints)
=> Fix multistrand/oligo bugs

lib/NUPACK/CMakeLists.txt, lib/NUPACK/emscripten/Bindings.cpp, lib/NUPACK/emscripten/FullEnsemble.cpp, lib/NUPACK/emscripten/FullEnsemble.h, lib/contrafold/.gitignore, package-lock.json, package.json, src/eterna/folding/Folder.ts, src/eterna/folding/NuPACK.ts, src/eterna/folding/__tests__/Folder.test.ts, src/eterna/folding/engines/NupackLib/index.d.ts, src/eterna/layout/RNApuzzler.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts
I modified  binding.cpp, fodler.test.ts, fodler.ts, index.d.ts,Nupakc.ts, PosEditMode.ts and RNApuzzler.ts I added the c++ files FullEnsemble.cpp and .h 
This change adds only the ability to run subopt module and get secondary structures from the ensemble at each predicted energy delta and free energy. It returns the data as a sting[][] with each index being an array of strings. The first is the structures, the seconds is the error, adn the 3rd is the free energy's each index of the arrays if for the same structure.
=> adding nupack functions for subopt structures and energies

src/eterna/folding/NuPACK.ts, src/eterna/folding/__tests__/NuPACKMultistrand.test.ts, src/eterna/pose2D/RNALayout.ts, src/eterna/pose2D/__tests__/RNALayout.test.ts, src/eterna/rnatypes/Sequence.ts
* Fix substructure energies being paced at the wrong locations. Start base indices of score nodes were incorrectly offset to account for cut points
* Fix missing substructure energies/very large total energy values in situations with disconnected strands. When computing energy with a disconnected strand, secondary strands had their bases shifted twice when computing strand energies separately
* Fix delta/total free energy mismatch (which wound up being incorrect total free energy values). The root node of a scored RNA tree didn't account for the multistrand energy adjustment
Big thanks to @LunarFawn for doing the initial investigation and pairing with me on this!
Resolves #658
=> Fix energy computation bugs in multistrand puzzles

src/eterna/pose2D/Pose2D.ts
When in simple graphics mode, if you mutate a base, it would slightly offset the base positions
This was because we perform the same animation we use randomly over time on loops whenever you mutate a base. However, in low performance mode, a future update sets the animation to disabled, causing just a slight base movement. This patch checks if simple graphics mode is enabled before attempting to start animating
Manual
=> Don't attempt to animate bases on mutate when in simple graphics mode

src/eterna/mode/DesignBrowser/DataCol.ts
For the "darker" design browser columns (which don't have a semi-transparent white background), clicking or hovering over areas without content would previously not trigger mouse events for the relevant rows. 
This is a regression due to a change in Pixi 6 affecting undefined behavior of whether graphics drawn with an alpha of 0 would be included in a hit test for mouse events. In other areas of the code, we draw the graphics with a higher alpha on the fill and then change the alpha of the graphics, but in this case the graphics contains portions which should not be affected by the alpha, so the simplest solution is making the alpha very small but not zero (which especially in this scenario is imperceptible).
Manual
=> Fix sections of design browser columns not being clickable

assets/RNABase/base-lock.svg
This is a super subtle change, but by making the height of the "body" of the lock slightly larger (relative to the height of the shackle and the width of the body), it helps the icon to read a bit more clearly
First image is the new version, second is the old version
Followup to #679
=> Increase height of body of lock icon

src/eterna/puzzle/Puzzle.ts, src/eterna/puzzle/PuzzleManager.ts
Going forward, we are expecting to have synthesis runs that would have more sequences than we could currently make unique barcodes for with only a barcode of length 7. This takes the recent backend update adding a barcode length field and uses it when determining the barcode indices, falling back to the previous value of 7 if not specified.
This logic mirrors the updated backend logic. I've opted to have the barcode "count back" from the tail if a barcode start is not specified in order to be more robust. Behavior if the barcode is placed past the end of the RNA remains unhandled, and is considered a reasonable setup error.
Ensured proper validation behavior in the following scenarios:
* No barcode start or length, unused barcode
* No barcode start or length, used barcode
* Barcode length …
=> Support variable barcode lengths

lib/EternaFold/CMakeLists.txt, lib/LinearFold/CMakeLists.txt, lib/NUPACK/CMakeLists.txt, lib/RNApuzzler/CMakeLists.txt, lib/Vienna1/CMakeLists.txt, lib/Vienna2/CMakeLists.txt, lib/contrafold/CMakeLists.txt, src/eterna/emscripten/EmscriptenUtil.ts
This includes a handful of changes to account for recent(ish) changes in Emscripten that caused issues when compiling with newer versions
* In 3.1.27 (released 11/29/22), the default stack size was reduced from 5MB to 64KB. We need larger available stack space, so we revert this setting
* In v1.38.41 (released 08/07/2019), callMain was no longer exported by default. Only nupack exports a main function we intend to call, so we enabled it specifically for that module
* `-Wimplicit-int` and `-Wint-conversion` were enabled, but cause errors in vendor Vienna code. We revert those errors to warnings.
* In 1.39.16 (released 05/15/2020), Emscripten modules now provide an actual promise instead of a "promise-like" interface, which we now use 
Basic sanity checks loading puzzles, unit tests
=> Update WASM components to compile + load under newer emscripten versions

lib/NUPACK/CMakeLists.txt
On the PK100 test puzzle (177 bases with pseudoknots enabled), we were getting memory allocation failures due to more memory being requested than available. By default, Emscripten has a memory limit of 2GB. Increasing to 4GB allows this puzzle to run, though this amount of memory usage could be problematic on lower-end devices (already, mobile devices were failing to load the PK90 within the old memory limit).
See https://github.com/emscripten-core/emscripten/blob/de7cbc56c3ac38b83cc3e8bbc17ac5fbb6b3bbd7/src/settings.js#L155-L175 for additional details on this parameter
PK100 now loads
=> Increase nupack maximum memory to 4GB

package-lock.json, package.json
Bumps optional dependency for prebuilt folding engines, including changes from https://github.com/eternagame/EternaJS/pull/686 and https://github.com/eternagame/EternaJS/pull/687
=> Bump prebuilt folding engine dependency

src/eterna/mode/PoseEdit/PoseEditMode.ts
Researchers want to do post-hoc analysis on designs, and in particular want to have access to the player's target structure and natural mode structure at the time of submission. This changes our previous system for caching long-running multistrand calculations to handle this use case
There are a number of idiosyncrasies in this patch which are documented through inline comments
Submitted new test lab designs, loaded designs with and without submitted fold data
=> Always cache undoblocks for submitted lab solutions

src/eterna/mode/FeedbackViewMode.ts, src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/ui/PasteStructureDialog.ts
Using magic glue to specify a target structure can be painful if you already have a particular target structure in mind that requires many changes, especially if loading from an external tool. This allows for a dot bracket target structure to be pasted directly.
Multiple users have also requested being able to copy structures, and this will also help if wanting to make the target structure match the current natural structure.
Currently this has just been added to the context menu (to expedite not needing a new icon, etc and also because for puzzles with pip mode, it's the quickest way that came to mind to figure out which state to apply to). The UX could definitely use improvement.
* Copied target and natural structures
* Pasted alternative structure changing constrained regions with and …
=> Support structure copy and paste target structure

src/eterna/EternaApp.ts, src/eterna/folding/Eternafold.ts, src/eterna/folding/EternafoldThreshknot.ts, src/eterna/folding/__tests__/EternafoldThreshknot.test.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
This commit adds a new folding engine that uses Eternafold for the initial base pair probability generation, then uses the Threshknot heuristic (https://arxiv.org/abs/1912.12796) to evaluate the bpp matrix and generate pairs (including pseudoknots). This engine is being implemented for use in the Pseudoknot project, with the goal of greatly speeding up computation time compared to NuPACK+PK.
These heuristic algorithms (Threshknot, Hungarian, etc) take the base pair probability matrix output of a folding engine and use it to select base pairs and generate a structure. As such, they can be applied to any folding engine that can output a base pair probability matrix. We currently have no way to add a post-fold processing step into the folding pipeline, so the simplest approach was to create …
=> Add Eternafold + Threshknot folding engine

src/eterna/ui/GameDropdown.ts
Previously, when calculating the width of the dropdown based on its contents, it could either either be higher or lower than it should be.
We now base the width of the current selected "box" on the size of the actual width of the current selected text or the popup, depending on whether or not changing is disabled, rather than using a rough calculation based on font size, and have that impact the popup size. Also, since the textballoons in the popup define their own padding, we make sure that is accounted for appropriately. There's a lot of potential room for cleanup in the future.
Manual, with different combinations of available folders, test with disabled state
=> Fix dropdown auto-width

src/eterna/pose2D/BaseAssets.ts
Old
New
Due to the removal of MSAA on rendered textures (2e61088c6d505015554304b24f28f685b096f16f), the smallest lock graphic comes across as square. This adds a bit of blur and FXAA to improve the antialiasing.
Reported by Eli Fisker
=> Make smallest base lock graphic look rounder

src/eterna/UndoBlock.ts, src/eterna/constraints/constraints/TargetExpectedAccuracyConstraint.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/ui/SpecBoxDialog.ts
Previously, pseudoknotted structures were showing "empty" specs in the specbox and when solutions were uploaded. Additionally, The melt plot was only (correctly) calculating the % unpaired at 37 degrees, instead of at each 10-degree interval
The first issue is due to stats inconsistently being stored/retrieved as having pknots enabled or not. The latter issue is due to getPairs returning an empty structure when pairs are not available where it was being checked against being null (due to a refactoring)
=> Fix specs with pseudoknots and melt plot

src/eterna/pose2D/BaseAssets.ts, src/eterna/pose2D/BaseTextures.ts
This improves the visual quality of bases at zoom level 4 (second-to-most zoomed out)
Old
New
=> Improve zoom level 4 base antialiasing

src/eterna/EPars.ts, src/eterna/UndoBlock.ts, src/eterna/constraints/constraints/ShapeConstraint.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/ui/ConfirmTargetDialog.ts, src/eterna/ui/PasteStructureDialog.ts
* The paste target structure dialog now has a button that will reset the target structure to the puzzle's default
* When submitting an experimental puzzle, if you have a custom target structure where there are pairs in the custom region which are invalid, confirm that the custom target is intended (with an option to reset).
* This PR also implements improved validation for pasted target structures
* The SHAPE and ANTISHAPE constraints contained custom logic to handle alternate oligo ordering when referencing the structure constraints and native structure. These have been moved into undoblock for reusability. 
* On experimental puzzle submission, we now create a "pipeline" of validation steps. This allows for moving from one step to the next easily when either validation passes or after …
=> Custom target structure improvements

src/eterna/debug/TestMode.ts, src/eterna/ui/ScrollContainer.ts
Currently, at least in certain situations, interactions with items in potentially-scrollable regions do not properly fire interaction events.
My guess is that something in the new event system changed behavior. Regardless, my initial comment about "touch events don't have a location" was wrong, and this handles them appropriately (or at least, I hope good enough - may want to do more testing with multitouch at some point).
Clicking the submit button in the Chrome mobile emulator with touch emulation now works
=> Fix touchscreen interactions with potentially-scrollable regions

src/eterna/ui/ScrollContainer.ts
A player reported the following issue on mobile
This resolves that error
Not only is `touches` not always available on `touchend`, but we always want to use `changedTouches`, as that is both always defined and correlates to the actual pointer which is triggering the event, which is what we should be filtering on
Clicking/dragging/releasing over buttons, inputs, and background in submit dialog, masked overlapping elements in end screen dialog. Tested with firefox touch emulation
This addresses issues introduced in #697
=> Fix errors interacting in scrollable regions on touch devices

src/eterna/mode/PoseEdit/PoseEditMode.ts
Currently, when pasting a target structure with an offset, the result can wind up being incorrect. This is because unpaired bases in the pasted structure are also having their pairing partner being adjusted by the offset, even though it should be left as -1. This could surface in one of three ways:
1) A user may see the dialog warning about invalid target pairs even though it appears to be fully valid
2) The visible target structure may be incorrect
3) In either case, the resulting recorded target structure will be incorrect. Whether or not there are errors beyond bases that should be `-1` being offset depends on the initial structure.
Validated correct behavior in 11627601 with sample sequence and structure provided by DigitalEmbrace
=> Fix offset target structure paste recording unpaired bases incorrectly

src/eterna/Feedback.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/puzzle/SolutionManager.ts
In the feedback mode, historically we've always computed the "estimate" structure by passing the sequence and SHAPE data to Vienna. This allows us to specify an estimate through other methods - in particular important for the pseudoknot challenge where pseudoknots are required.
Loaded a design as-is, then reloaded it after specifying estimate_structure in its synthesis data in the backend
=> Support precomputed estimate structure

package-lock.json, package.json, src/eterna/mode/FeedbackViewMode.ts, src/eterna/puzzle/SolutionManager.ts
* Enables pknots in pose2D if the puzzle uses pknots
* Parses the target structure with pknots if the puzzle uses pknots
* Don't set the score folder (used for substructure energies, aligned with Vienna being used for structure prediction) if the puzzle uses pknots
* Always parse the estimate structure with pknots
Validated loading solutions in PK90
=> Fix pseudoknot display in feedback mode

src/eterna/pose2D/RNALayout.ts
When loading in the PK pilot data with precomputed estimate structures, some contrafold-derived structures caused a crash in RNALayout. While impossible in nature, Contrafold can predict 0-length hairpins, which we did not handle.
I have opted to allocate a "virtual" node for the 0n hairpin like we do for other hairpins. This should mean that if an NNFE calculation generates a score for this node it will display, otherwise it will show as 0.
Loaded design 11438186 in puzzle 11318423 (estimate mode)
=> Support drawing 0-length hairpins

src/eterna/mode/DesignBrowser/DesignBrowserMode.ts, src/eterna/mode/ErrorDialogMode.ts, src/eterna/puzzle/SolutionManager.ts
A while back, we implemented permission/access rules for viewing designs. This has commonly caused confusion where a user tries to view designs and is left with a blank screen, not realizing they aren't logged in. This change surfaces such errors to the user so they are aware of what happened.
Loaded puzzle as an unauthenticated user
=> Surface reason for design browser load failure

src/eterna/UndoBlock.ts, src/eterna/constraints/constraints/BranchinessConstraint.ts, src/eterna/constraints/constraints/MaximumPairConstraint.ts, src/eterna/constraints/constraints/MinimumPairConstraint.ts, src/eterna/constraints/constraints/MinimumStackLengthConstraint.ts, src/eterna/constraints/constraints/PseudoknotConstraint.ts, src/eterna/constraints/constraints/RangePairedMaxConstraint.ts, src/eterna/constraints/constraints/TargetExpectedAccuracyConstraint.ts, src/eterna/folding/Contrafold.ts, src/eterna/folding/Eternafold.ts, src/eterna/folding/EternafoldThreshknot.ts, src/eterna/folding/Folder.ts, src/eterna/folding/LinearFoldBase.ts, src/eterna/folding/NuPACK.ts, src/eterna/folding/RNAFoldBasic.ts, src/eterna/folding/Vienna.ts, src/eterna/folding/Vienna2.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/puzzle/Puzzle.ts, src/eterna/ui/SpecBoxDialog.ts
We have a static variable for our default folding temperature, but in many situations we used the magic number 37 instead of that variable. This ensures consistent usage of the static variable
Basic smoke checks on 20111 (simple hairpin) and 11627601 (PK100)
=> Consistently use EPars.DEFAULT_TEMPERATURE instead of magic number

src/eterna/UndoBlock.ts, src/eterna/constraints/constraints/RangePairedMaxConstraint.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
This fixes a few remaining issues where the `pseudoknotted` parameter wasn't being set in UndoBlock parameter retrievals where it should have been
=> Correct eternascript structure, RangePairedMaxConstraint, mfe dot plot with pseudoknots

src/eterna/mode/PoseEdit/PoseEditMode.ts
The addition of this API allows authors to get the current target structure, which may have been modified the player, instead of just the puzzle-defined target (accessible via get_targets)
Validated on the PK100
=> Add Eternascript get_target_structure API to get current target structure

src/eterna/mode/PoseEdit/PoseEditMode.ts
This provides script authors (eg, for the mutation/submission booster) a convenient and reliable way to submit solutions (without manually constructing a POST request, which is awkward and could result in incorrect validation or missing information (eg, the undoblock with the custom target not being included)
* For multiple reasons, this has to be async. Promises seemed like the cleanest and most flexible way to do this.
* This API distinguishes between "hard errors" (ie, required validation failed, the backend returned an error, etc) which actually reject the promise and "user cancellation" which causes the promise to resolve to `false`. This allows for script authors to handle these situations differently ("this errored" vs "the user was prompted and opted to bail" are semantically …
=> Add eternascript submit_solution API

src/eterna/mode/FeedbackViewMode.ts
Previously when viewing structures in feedback mode with the rnapuzzler clash-free layout enabled, the tha RNA would be positioned far-offscreen with a high distance between bases. PoseEdit and PuzzleEdit would display the same structure correctly.
The issue was in feedback mode, we weren't passing the target structure to the pose, which we need to reference in rnalyout in order to apply correct scaling when laying out with rnapuzzler
Verified layout correctness with https://eternagame.org/game/browse/11318423/?filter1=Id&filter1_arg1=11459092&filter1_arg2=11459092
=> Fix rnapuzzler clash-free layout in feedback mode

src/eterna/mode/FeedbackViewMode.ts, src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/flashbang/core/AppMode.ts
Previously, there were a number of hotkeys available in the puzzle solver that shouldve been available in the puzzlemaker and feedback mode but were not.
This moves handling most hotkeys to the base GameMode class. Note that the design browser also extends from game mode, and in that case the hotkeys don't make sense. For that reason, we only "register" the hotkeys related to the RNA when there are poses available
Tried a combination of hotkeys in each mode
https://forum.eternagame.org/t/puzzlemaker/3086
=> Make hotkeys more consistenly available across modes

src/eterna/Feedback.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/puzzle/SolutionManager.ts
Feedback mode now properly parses multiple SHAPE conditions in solution experimental data and uses the last-selected SHAPE condition as the basis of the estimate mode structure. Additionally, condition names in the dropdown are prefixed by the experimental method (SHAPE or Degradation)
Still left unhandled is estimate mode when there are no available SHAPE conditions. In that case, we should remove the estimate mode button (and switch back to target mode if we're not already), but that implementation is not completely trivial, that hasn't happened yet, and everything still works if you don't switch to estimate mode
Ensured experimental data and estimate structure displayed and updated properly given:
* Single shape condition
* Multiple shape conditions
* Multiple shape conditions + …
=> Support multiple SHAPE conditions in feedback mode

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/rscript/ROPHighlight.ts, src/eterna/rscript/RScriptEnv.ts, src/eterna/rscript/RScriptUIElement.ts, src/eterna/ui/FolderSwitcher.ts
This allows for eg the hideui tutorial script command to work with the folding engine display/switcher
Making this change was largely comparing against all places RScriptUIElementID.SWITCH was used and replicating that. Additionally, I did a little cleanup in showHideUI to improve the clarity around elements that skip being hidden
Tested ShowUIArrow and #pre-hideui on both FOLDER and SWITCH (due to the tweak in handling of SWITCH and other fallthrough cases).
Resolves #724
=> Support folding engine switcher as a valid target for tutorial script UI commands

src/eterna/rscript/RNAScript.ts, src/eterna/rscript/ROPPre.ts
A number of rscript commands were not case insensitive, even though all of them should be. They are now all case insensitive
The regex /i flag was missing on some newer commands. I also removed /g flags since none of them should match multiple times
Manually ran tutorial scripts with showuiarrow and showtextboxnucleotide
Resolves #737
=> Make tutorial script instructions consistently case insensitive

src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
Clicking the structure constraint thumbnail in puzzlemaker highlights incorrectly-folding regions of the puzzle, just like in the puzzle solver
I've opted to move the highlight handling into the base class. This required moving `_poseState` into the base class as well. More general improvements to what the base class handles needs larger improvements, but this change seemed reasonably nondisruptive
Verified by hand click-to-highlight still works in puzzle solver as well as verifying in editor
Resolves #461
=> Support highlighting misfolding regions in puzzlemaker

src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/pose3D/Pose3DDialog.ts, src/eterna/puzzle/Puzzle.ts
- Show a message instead of crashing when trying to beam with oligos
- Beam 3D structure
- Beam locks
- Beam custom layout
- Autosave 3D structure
- Autosave locks
- Autosave custom layout
- Autosave molecule
- Autosave folding engine
- Promote EternaFold to default
- Remove EternaFold notice
There is some weirdness around data being pose-dependent vs not, coming from pose vs separate undo arrays, etc. I tried to be as consistent with the current code as possible
Tried beam/autosave load for each feature
Resolves #726
Resolves #174
=> Improve handled data in beam to puzzlemaker and puzzlemaker autosave

src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/ui/toolbar/Toolbar.ts
Being able to see the dot plot and additional specs in puzzlemaker can be useful in a variety of cases
be it to help solve an in-progress puzzle, work on a "partial" extracted from a puzzle, or
otherwise perform analysis with a free-form modifiable structure.
This is particularly important for the upcoming integration of RibonanzaNet, where we want to encourage players
to experiment with the behavior of the model, and both the dot plot and upcoming eF1 metrics will be important
for this
Opened specbox in puzzlemaker + made changes to puzzle
Split off from #748
=> Support specbox in puzzlemaker

src/eterna/folding/Contrafold.ts, src/eterna/folding/Eternafold.ts, src/eterna/folding/EternafoldThreshknot.ts, src/eterna/folding/Folder.ts, src/eterna/folding/LinearFoldBase.ts, src/eterna/folding/NuPACK.ts, src/eterna/folding/RNNet.ts, src/eterna/folding/Vienna.ts, src/eterna/folding/Vienna2.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/pose2D/Pose2D.ts, src/eterna/pose2D/PoseField.ts
* Puzzlemaker now properly shows energies as disabled for engines that cant score with pseudoknots
* Energies are noted as unavailable instead of hidden for both pknot cases as well as engines that cant score
* Switching between engines with and without energies available now consistently enables and disables energies
Instead of conditionally setting the scoreFolder based on canScoreStructures and then checking the pseudoknotted case,
canScoreStructures now takes a parameter for whether or not pknots are enabled, and skipping computations
is now handled just within Pose2D. This avoids logic for whether an engine can score being split in multiple
places.
Raised as part of #748
=> Consistently disable energies when unavailable

webpack.common.js, webpack.dev.js, webpack.prod.js
Previously, we always used inline-source-map for generating sourcemaps. Now in prod we use source-map to split the sourcemaps into separate files (which significantly reduces our bundle size) and in dev we use eval-source-map, which is faster
=> Improve sourcemap behavior

src/eterna/UndoBlock.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts
* There are now new async versions of EternaScript methods which trigger folding operations. This allows usage with async-only folding engines, as well as allowing scripts to use more efficient or user friendly behavior that is only available when folding happens async
* When calling any EternaScript getter or setter, we now verify that there are no asyncronous folding operations in process to avoid getting out of sync. This could happen already even with the existing syncronous APIs, as a user could trigger an asynchronous fold and then a script could trigger a synchronous fold before the async fold finishes.
* Fixed inverted error messages for sync/async behavior in specbox updates
* We now wait until the specbox is fully updated before unlocking the UI after a fold (and run …
=> Support async folding operations in EternaScript

src/eterna/EternaApp.ts
When immediately loading a solution in copy and view mode (not via the design browser), the app would crash as it required the solution list, which was not previously passed
=> Fix crash when immediately loading an existing solution

src/eterna/mode/GameMode.ts
Currently, when a "UI lock" is created (which dims the screen and prevents mouse/keyboard input below it),
it is positioned under all dialogs. This means that any existing dialogs can still be interacted with.
This updates the behavior to instead place the lock at the top of the dialog layer, such that existing
dialogs will be under the lock, but new dialogs will be over the lock.
The git blame indicates this behavior was introduced with screenshot posting. Testing screenshots with
this change, it seemed to behave fine. Either our dialog handling has somehow changed since then,
or it was changed proactively with the assumption that dialogs were always "exceptional" (eg, notifications,
confirmation dialogs, etc) - however now we use dialogs more extensively with the new windowing system …
=> Draw UI lock over all existing dialogs

src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/Booster.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/pose2D/Pose2D.ts
Improves code clarity and robustness to race conditions related to asynchronous folding
Unless we are in synchronous script mode, whenever a folding operation (or really, anything that requires state to be resynced/an undo state to be created) is triggered, the update is actually queued and run on the next game tick/update cycle - and could in fact be an asynchronous operation which does not complete for some time, even though the game continues to run (though under a UI lock). I've gone through and audited instances where we appear to perform actions immediately after we trigger a fold without waiting for the fold to complete.
I've now verified that we now only trigger async behaviors in callbacks, and if not explicitly awaited, is the very last thing to happen in the callback. The only …
=> Ensure all actions that require folding to complete actually wait

src/flashbang/util/ErrorUtil.ts
Minimally, in some cases we may catch a string as an error - we can easily display that. Also, in case we happen upon some other types, at least give some indication of what the error that was thrown was
=> Expand variety of error types that can be displayed

src/eterna/mode/PoseEdit/PoseEditMode.ts
Eg so that network errors (which are thrown as strings) dont come across as empty text
=> Improve error message when 3D view fails to load

src/eterna/Eterna.ts
Previously, in some cases (eg, during puzzle load or during fold processing) unhandled errors would cause the app to freeze without displaying the error (or allowing the possibility to try continuing).
The issue was that if the error was thrown as part of the update loop, which is initially triggered by the Pixi ticker's update, and so since the ticker update function is interrupted, the next frame is never queued (and so we never do the mode transition, animate in the dialog, or otherwise keep updating).
=> Ensure error dialog is displayed if error is encountered in update loop

src/eterna/constraints/Constraint.ts, src/eterna/constraints/constraints/ScriptConstraint.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts
Script constraints may call various methods that we've started to lock during folding - most obviously, constraints probably need to access the current solution to know whether it passes the constraint or not. Unfortunately, we can't really limit this to a set of reasonable methods (eg, just getters) because there are a bunch of constraints that currently hack in additional functionality this way.
It is still possible that there are some edge cases (eg, a constraint that does some very fast async work which yields the special external interface context and then goes and uses one of these methods before the regular lock releases), but I'm going to leave it like this to attempt being at least a bit safer and hope it doesn't cause issues (and if it does, it's likely it would wind up having …
=> Don't lock script methods during folding if called from script constraints

src/eterna/mode/PoseEdit/Booster.ts
When executing a booster, we provide it with a context which overrides the set_sequence_string method so that "paint tool" scripts can act directly on the pose during the paint process (eg, allowing a temporary mutation during a mouse move, and avoiding conflicts between the "UI-based" mutation process which was initiated and "script-based" mutation, both of could otherwise trigger fold/undo operations).
However, this method is always overridden and did not change when we changed the base implementation to accommodate async folding (which means the additional checks would not be present when this method is called from a synchronous script). This instead only overrides the method for paint tool scripts, allowing the base implementation to be directly used in all other cases
=> Fix set_sequence_string being overridden with a version without async handling

src/eterna/mode/GameMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts
Currently, when the UI is locked, the sidebar can still be interacted with. This is now prevented.
* This would be trivially solved if the sidebar could be under dialogs (where it realistically belongs). However, due to it containing HTML content that would render over other dialogs, we do not allow this. Therefore I instead draw a second lock dialog on top of the sidebar layer and mask it to where the sidebar is.
* I also handle "modal dialogs", which should have the same effect of locking the UI. However in this case, I also hide the sidebar entirely since otherwise you may not be able to see/interact with part of the likely statically-positioned dialog if the screen is small enough.
* The use of `any` here is due to typescript generic inference limitations. This is type safe from the …
=> Fix UI locks not applying to info sidebar

src/eterna/mode/PoseEdit/Booster.ts, src/eterna/ui/toolbar/Toolbar.ts
This fixes a bug in puzzles like https://eternagame.org/puzzles/8787266/play where we have multiple "dynamic"/script-based paint tools (eg in this case, two MS2 stamper variants) where interacting with the toolbar buttons can select both, hotbar setup can grab the wrong one, etc.
We assumed that these paint tools would always have a unique label. It appears that the label property is not always present, so we instead generate a unique ID.
=> Fix improper disambiguation with multiple dynamic paint tools

src/eterna/UndoBlock.ts
This fixes an issue where viewing the dot plot of a previously submitted solution would display a blank area instead of the dot plot
In a0c49d3148f69e9990c79b62139783ba3a5bd29f we started removing dot plot and melt plot data from the fold data uploaded with a solution. Specifically, we set those properties to null. However, when we check if we need to calculate that information, we only checked if it is undefined - meaning that in these cases where it was set to null, we'd treat the dot plot as already present and not (re)compute it. We now trigger the computation if it is either null or undefined (both cases where it is not already available).
=> Fix viewing dot plot of existing solution

src/eterna/folding/RNNet.ts
This fixes an issue where we created a new instance of the RNNet model every time we perform a fold instead of instantiating it once the first time it's run and then reusing it (causing runaway memory usage and adding additional unnecessary computation overhead).
We changed to "memoizing" the inference session so that we could only load rnnet when required instead of always loading it when the app starts. However, I neglected to actually save the value after initializing it, so it was always recreated (plus it appears that due to the implementation of InferenceSession, its resources are not released when it goes out of scope).
=> Fix rnnet not reusing created inference sessions

src/eterna/net/GameClient.ts, src/eterna/puzzle/SolutionManager.ts
Currently, we're hitting memory limits in our API due to the amount of data we pull back when loading all solutions at once. This now breaks up loading solutions into multiple requests.
=> Incrementally load solutions

src/eterna/pose2D/BaseRope.ts
This fixes a crash that would occur if the base rope is enabled for a puzzle where there is a strand only
one nucleotide long (eg, the openvaccine "leaderboard puzzles")
The bug would actually occur internally to pchip, where it would attempt to get the second point, which does not exist
Ran "normal" and 1-nt puzzle with base rope enabled and disabled
=> Fix crash when trying to draw base rope with only one nucleotide

src/eterna/rnatypes/SecStruct.ts, src/eterna/rnatypes/__tests__/SecStruct.test.ts, src/eterna/rnatypes/__tests__/__snapshots__/SecStruct.test.ts.snap
* Handle pseudoknotted dot-bracket strings where uppercase letters occur before lowercase letters
* Differentiate unbalanced parenthesis and unknown character errors (and clarify wording)
* Error if pairs are opened but never closed
* Remove assign-in-conditional optimization (realistically this was probably an over-optimization needlessly reducing readability)
* Adjust case order for clarity (and, possibly a small performance gain)
* Add additional comments
* Add test cases for error scenarios
Unit tests
Additional work in service of #789
=> Dot-bracket parsing reversed capitalization support + better errors

src/eterna/constraints/constraints/ScriptConstraint.ts
If a SCRIPT constraint errors, we currently throw an error with the error details we were provided. However, this can be opaque, especially in Chrome where you can encounter errors like "Cannot read properties of undefined" without the name of the variable. Now, we explicitly note that we've encountered an error in a SCRIPT constraint and which script it was. Since the error could be caused by a misconfiguration by the puzzle author, this also may help the puzzle author identify and troubleshoot the issue.
=> Provide info about script constraint when encountering an error

src/eterna/constraints/constraints/ConfidenceConstraint.ts
To prevent potential overlap if we create new constraints with alternate methods for handling PKs
=> Rename BPPF1NATIVEPKMIN to BPPF1NATIVEPKMASKMIN

src/eterna/constraints/constraints/ConfidenceConstraint.ts, src/eterna/rnatypes/SecStruct.ts
There were a few bugs which caused the confidence constraint calculation for pseudoknots to be incorect:
* The desired pairs were marked as all pairs, not just crossed pairs
* Some pairing probabilities were not considered when they should have been, as checking which pairs were crossed only worked from one side of the pair
* Indices of base pairs which should have been zeroed out were off by one
The issue with getCrossedPairs having some pairs only filled out from one side technically had effects beyond this, but this was the only case where it caused an error (its other use is in RNNet.getEf1CrossPair, which only relies on the "lower half" of the pair being filled out
Continues #791
=> Fix bugs in PK confidence constraint

src/eterna/constraints/constraints/ConfidenceConstraint.ts
Currently when we go to calculate the PK confidence of a structure with no PKs, it will display as 0.667. This "corrects" the behavior to display 0
This is because since all bpp contributions would be zeroed out, f1 would be calculated as (2 * 1e6) / (2 * 1e6 + 1e6 - 1e6 + 1e6) = 0.666666666. Really it's undefined (the 1e6 default values are there to prevent that) and "0" is better reflecting our intent
Continues #791
=> Set PK confidence to 0 when no PK pairs

src/eterna/constraints/constraints/ConfidenceConstraint.ts
To help disambiguate with other potential methods of determining confidence
Continues #791
=> Add additional deatils about the specific metric being used for confidence in tooltip

src/eterna/mode/PoseEdit/PoseEditMode.ts
Previously, when switching between designs with next/previous, constraints like the confidence constraint which requires the dot plot to be computed would fail to update - and in fact, throw an error and not complete the solution load process - without a cached dot plot in the loaded solution.
There is a new util function loadCachedUndoBlocks. This avoids previous duplication with the (currently disabled) mutation-time fold cache, and moves this code closer to `poseEditByTarget` which is the "alternative" method for doing this kind of work (and maybe eventually we can improve unification between these codepaths). The main goal here is to at least avoid doing the extra "folding operation" in a random part of the code we'd be liable to forget about if we need to tweak dot plot …
=> Fix crash/update failure with constraints requiring dotplots when loading a cached design

src/eterna/mode/PoseEdit/PoseEditMode.ts
Previously, we set the target structure for a solution after an undoblock was created. This was part historical artifact (eg, due to using pasteSequence to update the sequence which wound up creating a new undoblock, which was changed in #768). That said, I also didn't realize there was a better way: set `_targetPairs`/`_targetOligosOrder`, like what happens when magic glue is used - these are intended to be "scratch" variables that are updated with changes and propagated to the undoblock once it's created. This is simpler, more idiomatic, and avoids any special handling needed if we're in "freeze mode"
=> Avoid surgical updates of undo state when setting custom target structure from solution

src/eterna/puzzle/SolutionManager.ts
We've recently run into situations where errors are thrown when parsing solutions, eg due to an invalid estimate structure. This currently requires a fair amount of extra work to track down which solution is causing issues. Now, we explicitly include the ID of the solution that encountered an error in the error message.
Validated when loading design browser for a puzzle which had a solution with an invalid estimate structure
=> Display error with ID of solution if error is encountered when loading solution list

src/eterna/mode/DesignBrowser/ViewSolutionOverlay.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts
Currently, loading solutions while freeze mode is enabled can lead to various problematic behavior:
* Running expensive computations anyways (eg, when loadCachedUndoBlocks needs to trigger a dot plot update)
* Leaving some information out of date while other information is up to date, leading to potential player confusion (eg, if some information is not in the cached undo block and the previous state is used) - and potentially changing which information is out of date or not between designs based on whether/how much data is cached
* Crashes (eg, with no cached undo block and you try to load the native structure)
Now, we instead prevent changing solutions to avoid these cases
There are use cases where it could be valuable to scroll through designs while frozen, even if not all information …
=> Dont allow navigating solutions while frozen

src/eterna/mode/GameMode.ts
Previously when using the paste sequence dialog to eg paste in a subpuzzle using a value like "AUGC 5-8", it would crash
This issue was presumably introduced when I refactored sequence pasting. The paste sequence dialog parses the user input into a sequence with UNDEFINED bases at positions should remain unchanged, which previosly would be skipped, but we did not properly skip in the updated implementation 
Tested pasting in a sample sequence+range that previously failed
=> Fix crash when pasting a sequence for a specific subset of bases

assets/Styles/styles.css, src/eterna/EternaApp.ts, src/eterna/ui/ScrollContainer.ts
Currently if you eg have the sequence field in the design browser part way offscreen and then paste a long sequence, if will cause the entire page to shift offscreen. This prevents that from happening
By default, browsers move the page so that a focused input (and more specifically, your cursor) is in view. This makes sense, as you want to make sure you see what you're doing, and a keyboard user may be tabbing through input fields which should scroll into view, etc. However: a) scrolling the page is not actually what we want - we haven't actually drawn content there that's just sitting offscreen, it's only "virtually" in our scene and we'd actually need to redraw the scene and b) we have overflow: hidden on our root game element, which means that there is no good way to scroll the content …
=>  Prevent focusing inputs from causing page to scroll offscreen 

src/eterna/mode/PoseEdit/PoseEditMode.ts
Previously, the `energy_of_structure_async` Eternascript function was identical to `energy_of_structure`. Now, it is an async function returning a promise, as intended and described 
While no folder currently exposes scoreStructures as async, which is why this did not lead to a type error, and there is nothing for us to await, we are exposing this async version to allow users to future-proof for situations where async access may be required.
=> Fix energy_of_structure_async not returning a promise

src/eterna/UndoBlock.ts, src/eterna/constraints/constraints/ConfidenceConstraint.ts, src/eterna/folding/FoldUtil.ts, src/eterna/folding/__tests__/FoldUtil.test.ts, src/eterna/ui/SpecBoxDialog.ts
Following the addition of the confidence constraints (https://github.com/eternagame/EternaJS/issues/791), these metrics are now being added to the specbox
Also, BPP-derived metrics are now always recomputed when doing a dot plot update, to avoid the situation where some metrics may have been cached, but not all of them (ie, due to the calculation being done on an old version of the code where they did not exist), leaving some of them to not be left empty.
* eF1 is now removed since this is now the preferred metric. Its UndoBlockParam IDs are retained only for historical reference (note they can't be reused since there is saved data where these IDs already refer to eF1
* TEA is kept in the code to support the constraint, however removed from the specbox because its not meaningfully …
=> Add confidence metrics to specbox

src/eterna/EternaApp.ts
Previously, when switching to feedback mode we re-queried solutions, even if we already passed them from the design browser.
Also, even if it was required, it was being loaded *twice*. This changes the behavior to use the previously-fetched
solutions if available without refetching, and if a fetch is needed, only fetching once. This is particularly valuable for
puzzles with large amounts of solutions where it is time and memory intensive to load all solutions.
Loaded feedback view for OKR2 via design browser and directly
=> Fix solutions being reloaded when switching to feedback mode

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/rnatypes/SecStruct.ts
This actually resolves a couple issues:
1) A crash when using the t-loop stamper
2) Potentially unknown bugs when using the t-loop stamper due to a partially corrupted internal structure representation
3) When using either the t-loop stamper or target structure paste, there is a chance you could violate structure constraints (when pairing bases a and b, we never checked if b is paired to c, that c is able to be made unpaired)
Speaking to (1)/(2): What happened here is that the t-loop stamper was only configured to set pairs from 5' to 3' and not 3' to 5' (eg, in either stamp, we specified that the first base should be paired to the last base, but not that the last base should be paired to the first base). The crash occured if you stamped over an existing target structure such that …
=> Fix structure modifications sometimes leaving half-paired bases

src/eterna/EPars.ts, src/eterna/constraints/constraints/TLoopConstraint.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/pose2D/Pose2D.ts, src/eterna/ui/toolbar/Toolbar.ts, src/eterna/ui/toolbar/ToolbarButtons.ts
Discussed with Rhiju. Originally I had the impression that one of the sequences should always be before the other, but they can actually be in either order. The stamper already inadvertently stamped the structure in both orders, but now the constraint also allows it (and the UI + code is updated to refer to the two regions as a and b rather than 5' and 3')
=> Allow tloop to be formed with sequence regions in any order

src/eterna/mode/PoseEdit/PoseEditMode.ts
Otherwise we'd be stamping a structure that's not actually a valid tloop structure. The constraint verified this, but the stamp did not
=> Dont stamp tloop structure if the current stamped sequence overlaps with the other stamped sequence

src/eterna/folding/FoldUtil.ts
Conventionally, dot plots are probability matrices such that for any base, the probability that it will pair with any other base will sum to 1, less the probability that it is unpaired - with probability unpaired excluded, so to get the probability unpaired we sum and subtract from 1. However for an algorithm like ribonanzanet, the dot plot is instead a likelihood matrix such that the liklihood of each pair is independent of every other pair, meaning it could sum to more than 1. We now clip P(unp) to so that if the row sums to a value > 1, we don't drop p(unp) to be below 0, which doesn't make sense (it is still ambiguous what p(unp) should be if you have two pairs at .75 liklihood, but this is at least _better_).
This reflects a change made in https://github.com/DasLab/arnie/pull/50
=> Dont allow p(unpaired) to be less than 0

src/eterna/puzzle/SolutionManager.ts, src/eterna/rnatypes/SecStruct.ts
In some of our recent labs (eg OpenKnot round 4) padding, barcodes, and tails are not included in the puzzle, instead being added as part of the synthesis process. We want to support the raw, un-trimmed data to be uploaded to Eterna. This is partially so that at a later date we could actually show this information, but for now as a practical implementation matter (we can't do it in the scoring pipeline without creating an invalid RDAT, and the backend does not have access to the code necessary to properly trim the estimate structures).
The simplest path forward here appeared to be modifying the data on load rather than actually supporting visualizing the data at a given location. Naturally this would need to be adjusted if we decide to display the full data.
This has also uncovered a bug …
=> Support padded experimental data
