package-lock.json, src/eterna/folding/LinearFoldC.ts, src/eterna/folding/LinearFoldV.ts, src/eterna/folding/NuPACK.ts, src/eterna/folding/Vienna.ts, src/eterna/folding/Vienna2.ts, src/eterna/pose2D/Pose2D.ts
My first pull request.   Any feedback requested.
=> Fix193 - Put energy text on a separate layer

src/eterna/pose2D/RNALayout.ts
=> Add RotationDirection enum

lib/LinearFold/emscripten/FullFold.cpp, lib/README.md, lib/patch.sh, src/eterna/folding/__tests__/Folder.test.ts
We now work with the latest LinearFold, and our instructions suggest that it be obtained via specific detached HEAD checkout rather than just grabbing latest master.
=> Linearfold update

src/eterna/EternaApp.ts, src/eterna/mode/DesignBrowser/DataCol.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/puzzle/PuzzleManager.ts, src/eterna/util/Utility.ts, src/eterna/util/__tests__/Utility.test.ts
Fixes #213 - replace Utility.roundTo() with built-in number .toFixed() fuction.
Fixes #219 - but only one case occurred
=> Fix for a couple of minor code cleanup issues

src/eterna/mode/PoseEdit/MissionClearedPanel.ts
The result looks like this - let me know if it needs to be tweaked:
=> Wrap text inside an HTMLTextObject

src/eterna/mode/GameMode.ts
=> extra targetConditions check in GameMode

src/eterna/constraints/ConstraintBar.ts
Needed by [Nova Tutorial 2.2](https://www.pbs.org/wgbh/nova/labs/lab/rna/research#/nceg/2/2) / eterna-dev 9386698
resolves #285
=> Ensure directive 'WaitForClickUI shapeobjective' works

package-lock.json, package.json, src/eterna/EternaApp.ts, src/index.html.tmpl
=> Show warning message on mobile

src/flashbang/objects/Button.ts
=> Use pointerTap event to emit the click, instead of pointerUp

src/eterna/pose2D/Pose2D.ts, src/eterna/pose2D/PoseField.ts, src/flashbang/core/Flashbang.ts, src/flashbang/objects/Dragger.ts, src/index.html.tmpl
=> Ensure camera drag and nucleotide painting works on mobile

src/eterna/constraints/constraints/MinimumPairConstraint.ts
=> Fix space missing in MinimumPairConstraint description

src/eterna/mode/PoseEdit/MissionIntroMode.ts
resolves #307 
* The mission description is not word-wrapped and goes beyond the screen if too long
* Make sure constraints scrolling arrows are shown if needed only (constraint height bigger than available space)
* Better constraint scrolling bounds
=> Mission screen layout fixes

src/eterna/rscript/RScriptEnv.ts
The cleanup code was doing nothing because it wasn't iterating through a `map` the right way.
resolves #309
=> cleanup rscript ui on complete

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/ui/help/HelpToolTips.ts
=> If Palette is hidden, don't show its tooltip

assets/styles.css, src/eterna/Eterna.ts
Fixes broken overlays when running within Nova
=> add eterna specific prefix to overlay id

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/ui/help/HelpToolTips.ts
resolves #294 
Testable on eterna-dev puzzle `9386588`
=> Ensure undo/redo help tooltip is not show if undo ui is hidden

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> Hide help bar when entering mission cleared screen

.env, package-lock.json, src/eterna/EternaApp.ts, src/eterna/rscript/ROPPre.ts
- Saved sequence is cleared if an `rscript` is present.
- Removed `#PRE-ResetSequence` directive
=> Clear saved sequence if puzzle has a tutorial script

src/eterna/pose2D/Pose2D.ts, src/eterna/pose2D/PoseField.ts, src/flashbang/input/InputUtil.ts, src/flashbang/objects/Button.ts
=> Mobile pinch zoom

lib/LinearFold/linearfold-eterna.patch, src/eterna/folding/__tests__/Folder.test.ts
fix linearfoldC multiloop penalty sign (thanks, brourd and hoglahoo)
=> New unit tests

src/eterna/pose2D/Base.ts
=> Ensure invisible nucleotides are not clickable

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/pose2D/Pose2D.ts
=> Skip puzzle animation if there is a mission screen

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/settings/EternaSettings.ts, src/eterna/ui/GameDropdown.ts
=> Folders selected through dropdown

src/eterna/ui/TextInputObject.ts
=> text weight

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> URL updates when puzzle is changed

package-lock.json, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PoseEdit/SubmitPoseDialog.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/mode/PuzzleEdit/SubmitPuzzleDialog.ts
=> Solution and puzzle submit text boxes save inputs

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> Fix folder showing over constraint tooltip

src/eterna/mode/FeedbackViewMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
Resolves #397 
Adds the correct home button to the puzzlemaker and correctly positions the solution title in the feedback view
=> Feedback view and puzzlemaker use correct home button

src/eterna/mode/DesignBrowser/DesignBrowserMode.ts
=> Sequence column in design browser always has dark background

src/eterna/mode/DesignBrowser/DataCol.ts, src/eterna/mode/DesignBrowser/DesignBrowserMode.ts
=> Design browser rows are clickable on mobile

package-lock.json, package.json, src/eterna/pose2D/PoseField.ts, src/eterna/pose2D/lodash.debounce.d.ts
Resolves #80 
Uses some debounce magic along with recording scroll delta to make scrolling work with Magic Mice/Mouses. I've tested this with my Magic Mouses as well as with another normal mouse.
=> Magic mouse scrolls properly

assets/Styles/styles.css, src/eterna/mode/DesignBrowser/DataCol.ts, src/eterna/mode/DesignBrowser/DesignBrowserMode.ts, src/eterna/mode/DesignBrowser/SortOptionsDialog.ts, src/eterna/ui/UITheme.ts
Resolves #440 
Resolves #430 
Resolves #457
=> Change design browser font size back to 14

src/eterna/ui/GameDropdown.ts
=> Dropdown is as wide as selected item when disabled

src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
=> Filter available engines for switches in puzzlemaker

src/eterna/ui/SpecBox.ts
=> Specbox handles undefined target expected accuracy

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> Beaming to puzzlemaker works correctly in any state

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> Hint box is not visible in screenshots

src/eterna/mode/PoseEdit/MissionClearedPanel.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/puzzle/Puzzle.ts, src/eterna/puzzle/PuzzleManager.ts
=> Puzzles don't show bubbles if already solved

assets/Styles/styles.css, src/eterna/ui/HTMLTextObject.ts
I think this works. Resolves #480
=> HTML elements use overflow-wrap: break-word

src/eterna/EternaApp.ts, src/eterna/mode/DesignBrowser/DesignBrowserMode.ts, src/eterna/mode/DesignBrowser/ViewSolutionOverlay.ts, src/eterna/mode/FeedbackViewMode.ts
=> Hotkey and button work for prev/next puzzles in feedback view

src/eterna/mode/DesignBrowser/CustomizeColumnOrderDialog.ts, src/eterna/mode/DesignBrowser/DesignBrowserMode.ts, src/eterna/settings/EternaSettings.ts
=> Add option to display only solutions selected with control+click

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> Restore next puzzle button for tutorials already solved

package-lock.json, src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts, src/eterna/pose2D/RNALayout.ts
@Omei requested a script interface extension. Here you go.
=> get_custom_numbering function

package-lock.json, src/eterna/UndoBlock.ts
I think I was wrong about what was wrong about what I was fixing earlier, considering that this commit just straight-up breaks some stuff.
=> De facto reversion of a067d93d5

src/eterna/mode/DesignBrowser/DesignBrowserMode.ts, src/eterna/mode/FeedbackViewMode.ts, src/eterna/mode/PoseEdit/PoseEditMode.ts
This PR relies on #547 and #548 (which should be merged first. Changes were made in d2efb6e0cbf3d887ac8bf7cdcfe7ed513c485daa, earlier commits were from those two PRs.
=> Fix feedback view solution swapping

src/eterna/pose2D/BaseRope.ts, src/eterna/pose2D/Pose2D.ts, src/eterna/pose2D/PseudoknotLines.ts
Noticeable performance improvement on medium puzzles like: https://eternadev.org/game/puzzle/10197683/
=> Avoid cloning the full nucleotide sequence while iterating over it

package-lock.json, src/eterna/EPars.ts, src/eterna/constraints/constraints/MaximumNonLibraryMutationConstraint.ts, src/eterna/puzzle/PuzzleManager.ts, src/eterna/util/Utility.ts
@luxaritas perhaps ignore the package-lock changes; I just couldn't push otherwise.
=> Max non-library mutation constraint

README.md, lib/README.md
- Some clarifications, some polishing
- Adjusted location of *nix-specific info so Windows users would see it upfront instead of noticing it halfway through attempting an implementation
- Adjusted .env.local instructions to be consistent with default value for APP_SERVER_URL in .env
=> Update README files

src/eterna/util/Fonts.ts
Causing loading text to display in the wrong font
=> Fix not waiting for all font variants to load before showing loading text

package-lock.json, package.json
Lroppy reported that when typing in chat while it is hidden (ie, by the mission end screen coming up), the input box would disappear. See https://github.com/eternagame/eterna-chat-wrapper/commit/09fb09a65246084d559ad7518f6b2f5f6ece3bf8 for more details
=> Bump eterna-chat-wrapper to fix chat input dissapearing

src/eterna/mode/PoseEdit/PoseEditMode.ts, src/eterna/puzzle/Puzzle.ts, src/eterna/puzzle/PuzzleManager.ts
Supports adding a new field in the admin panel, "Next Puzzle Link" that overrides the "Next Puzzle" behavior to redirect to a hardcoded URL.
Checks for the field in the puzzle data sent from the backend. If present, the default behavior is overridden to redirect to a URL instead.
=> Add link redirect support to "What's next?" button

src/eterna/mode/DesignBrowser/DesignBrowserMode.ts, src/eterna/mode/ErrorDialogMode.ts
The main goal of this change is to use the updated dialog styling for the error dialog. Additionally I noticed that the error dialog in the design browser when failing to load solutions was being double-triggered due to two concurent requests. We really have no need to fire off new refreshes if we're already refreshing (it's just wasteful and potentially race-condition prone), so this change also ignores refresh requests when already refreshing
This also moves from the previous "raw" GamePanel approach of ErrorDialogMode to the mode "modern" GameWindow approach
Loaded design browser as an anonymous user
=> Use new dialog UI for error dialog, don't over-fetch solutions

src/eterna/mode/PoseEdit/PoseEditMode.ts
This exposes the ability for scripts to set a custom target structure. Behaviorally, this works just like the paste target structure dialog in the UI
* This refactors the code from the paste stucture dialog to a shared function which can be used in both situations
* I set forceSync to true since this causes a re-fold (ie, paste calls poseEditByTarget)
Pasted a simple target structure with/without a starting position in the UI and via the API
=> Add set_target_structure Eternascript API

src/eterna/mode/FeedbackViewMode.ts
Recently, we moved to always uploading cached undoblocks in lab puzzles in particular so that we could have access to the author's custom target structure. This was being displayed in pose edit mode (ie, when loaded with "copy and view") but not in feedback mode (when loaded with "see results"). This implements showing the custom target structure in feedback mode
As mentioned in the code, this is rather hacky, but I don't immediately see a better way to handle this that's relatively simple. We should revisit this.
Added experimental results from an older solution to a test solution on dev that had fold-data uplaoded and viewed in feedback mode (along with solutions that did not have data, which also display fine)
=> Show stored custom target structure in feedback view mode

src/eterna/mode/PoseEdit/PoseEditMode.ts
Previously, if you viewed a solution with cached fold data that included a custom target structure, then switched to a solution with no cached fold data, it would retain the custom target of the previous solution. This is liable to create confusion. Instead, we now reset to the puzzle's default target if not available.
Swapped between solutions on a test puzzle with with and without fold data/custom target available
=> Set solution target structure to puzzle default if no custom target available

lib/README.md
Update support email, explain ability to run EternaJS without building everything, separate out prereqs, clarify install locations, clarify what feature each lib is needed for, fix patchfile description, general cleanup
=> Lib setup instructions cleanup

src/eterna/mode/PoseEdit/PoseEditMode.ts
Currently, there is a potential race condition where between the initial load and
the target structure for the initial solution coming back, the puzzle could be modified,
causing the target structure to be set on the wrong undo item or solution. This change
avoids that by locking the UI during that time, preventing actions which could
change the currently loaded state/solution
=> Prevent potential desync when loading target structure for initial solution

src/eterna/mode/PoseEdit/PoseEditMode.ts
* Add docstrings to multiple methods that handle the core folding/state update flow
* Rename `processBaseShifts` to `syncUpdatesFromPose` to be more accurate
* Remove some unnecessary duplication from `syncUpdatesFromPose` by inverting a conditional (to avoid needing an early exit)
=> Improve clarity of poseEditByTarget series of methods

src/eterna/mode/PoseEdit/PoseEditMode.ts
=> Fix skipped required constraints when submitting from eternascript with validate false

src/eterna/mode/PoseEdit/PoseEditMode.ts
Currently, we have a warning message that displays if a region with an unconstrained target structure has target pairs that are not filled with bases that make valid pairs. This was to prevent the situation where a custom target structure is created, but is later modified (eg, by copying someone else's solution) while ignoring that target (ultimately, we want to avoid saving a bogus custom target structure).
However, this warning was also showing if the default target structure was left unchanged and the player elects to ignore it. Eg, in the OpenVaccine puzzles, we do provide a default target structure which is just a copy of the natural mode structure. The goal is to optimize degredation, which likely requires a different structure, and players should ignore the target entirely unless …
=> Dont show custom target warning if the target structure hasn't been changed from the default

src/eterna/ui/Dialog.ts
There are a number of situations when we "lock" the UI to user interaction, such as when a modal dialog is present or we're in the middle of folding. However, we weren't preventing interaction with the parts of the UI in the HTML overlay. One way this manifested was if you hovered over the script constraint codon chart while folding occurred, an error is thrown complaining about trying to use a getter/setter (in this case, get_sequence_string) while in the middle of folding.
The early handler shenanigans are borrowed from ScrollContainer. It might be a good idea at some point to move this stuff to some shared utility, or find a way around it all together, but I don't have the bandwidth to do that right now. This could be further improved if we could also apply "dimming" to the HTML UI, …
=> Prevent HTML UI interaction as part of UI/dialog locks

lib/RibonanzaNet/export_onnx.py, package-lock.json, package.json, src/eterna/EternaApp.ts, src/eterna/folding/RNet.ts, src/eterna/folding/__tests__/RNet.test.ts, src/eterna/folding/__tests__/__snapshots__/RNet.test.ts.snap, src/eterna/mode/PuzzleEdit/PuzzleEditMode.ts
The official abbreviation has changed
=> Rename internal references of RNNet to RNet
